# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt


    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        our_users:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.security.login_form_authenticator

            logout:
                path: /logout
                target: /login

            switch_user: ~
            # activate different ways to authenticate
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/setings, roles: ROLE_ADMIN }
        # - { path: ^/setings/*/, roles: ROLE_ADMIN }
        - { path: ^/user/*/, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
